#!/bin/bash

tap=$1
scripts_path=$(sh "/tmp/qemu_scripts_path.sh")
bridgeName=$(sh "$scripts_path/create_and_get_bridge.sh" "$tap")

echo "$bridgeName: Ready for $tap"

if sudo ifconfig "$bridgeName" addm "$tap" && \
  sudo ifconfig "$bridgeName" up; then

  echo "$tap: is ready"
else

  echo "ERROR: $bridgeName failed to initialize"
  sh "$scripts_path/fail_and_cleanup.sh" "$tap"
fi
