#!/bin/bash

tap=$1
if sh delete_bridge.sh "$tap"; then

  echo "Completed"
else

  echo "ERROR: Failed to complete with success"
fi

if ! sh is_macos.sh; then

  sudo systemctl unmask sleep.target suspend.target hibernate.target hybrid-sleep.target
fi