#!/bin/bash

bindBridgeTo="en0"
bridgeName=$(sh create_and_get_bridge.sh "$1")
echo "$bridgeName: Ready for $1"

if sudo ifconfig "$bridgeName" addm "$bindBridgeTo" addm "$1" &&
  echo "$bridgeName: bound with: $bindBridgeTo and $1" &&
  sudo ifconfig "$bridgeName" up; then

  echo "$1: is ready"
else

  echo "ERROR: $bridgeName failed to initialize"
  sh delete_bridge.sh "$1"
  exit 1
fi
